### PR TITLE
GE class now returns a JSON string when logged

### PR DESCRIPTION
**Pull request by benalleng**
because of how the monaco editor works, we can only read a single line console.log() from the backend so anything that is returned should be in a truncated format to then be modified on the frontend.

I think returning a JSON string is the best way in this case to show the user clear enough information and make it eassily parseable

### CODE REVIEW

**Comment by satsie** [comment]
Assigning myself to review this. This is used in Chapter 4 right? I was just in there not too long ago. I will review this PR after I finish doing a full play of the game.

**Comment by benalleng** [comment]
I actually think this is stale, we've modified the repl and it's capabilities quite a bit since then. I honestly can't remember if we implemented this in the frontend or not

**Comment by benalleng** [comment]
Here is what we actually landed on in our secp256k1 library

`[
inspect.custom]() {
    if (this.inf)
      return '(inf)'
    return `(${this.x.hex()}, ${this.y.hex()})`;
  }
}
`

**Comment by satsie** [comment]
Oh nice! I had no obvious issues with the GE class when I was doing chapter 4 so from my side things look good. I'll leave it up to you to decide if the PR is good to close. Thanks for looking into this so quickly!

**Pull request closed without merging**
